version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<REPLACED_AT_DEPLOYMENT>"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 80
